auths/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = "auths"
urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(next_page='auths:homepage'), name="logout"),
    path('', views.homepage, name="homepage")
]

story10/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('auths.urls')),
]

auths/models.py
from django.db import models

# Create your models here.

auths/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('auths:login')
    else:
        form = UserCreationForm()
    return render(request, 'register.html', {'form': form})

def homepage(request):
    return render(request, 'homepage.html')

auths/templates/homepage.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HOME</title>
</head>
<body>

    {%if user.is_authenticated%}
        Welcome, {{user.username}} <a href="{%url 'auths:logout'%}">[LOGOUT]</a>
    {%else%}
        <p>You are not logged in<a href="{%url 'auths:login'%}">[LOGIN]</a></p>
    {%endif%}

</body>
</html>

auths/templates/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>REGISTER</title>
</head>

<body>
    <div>
        <h1>Create New Account</h1>
        <form action="{% url 'auths:register' %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Register</button>
        </form> 
    </div>
</body>

</html>